# Generated by Django 5.2.5 on 2025-08-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_receiver', models.CharField(max_length=150)),
                ('id_announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_donations', to='books.announces')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_donations', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeDonationHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('id_exchangedonation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic', to='transactions.exchangedonation')),
            ],
        ),
    ]
