# Generated by Django 5.2.5 on 2025-09-10 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_announces_conservation_status_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangedonationhistoric',
            name='id_exchangedonation',
        ),
        migrations.AddField(
            model_name='exchangedonationhistoric',
            name='id_announce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.announces'),
        ),
        migrations.AddField(
            model_name='exchangedonationhistoric',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangedonationhistoric',
            name='user_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExchangeDonation',
        ),
    ]
