# Generated by Django 5.2.5 on 2025-08-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Status 1'), ('2', 'Status 2'), ('3', 'Status 3'), ('4', 'Status 4'), ('5', 'Status 5')], default='5', max_length=1)),
                ('description_status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('1', 'Exchange'), ('2', 'Donation')], default='1', max_length=1)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces_authored', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces_created', to='users.user')),
                ('conservation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces', to='books.conservationstatus')),
            ],
        ),
    ]
