# Generated by Django 5.2.5 on 2025-09-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announces',
            name='conservation_status',
            field=models.CharField(choices=[('1', 'Status 1'), ('2', 'Status 2'), ('3', 'Status 3'), ('4', 'Status 4'), ('5', 'Status 5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='announces',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces_authored', to='books.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='ImagesBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announces/')),
                ('is_cover', models.BooleanField(default=False)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.announces')),
            ],
        ),
        migrations.DeleteModel(
            name='ConservationStatus',
        ),
    ]
